[tool.poetry]
name = "pysemver"
version = "0.1.0"
description = ""
authors = ["Mauko Quiroga <mauko@pm.me>"]
packages = [{include = "pysemver", from = "src"}]

[tool.poetry.dependencies]
python = ">= 3.7, < 3.11"
numpy = ">= 1.18, < 1.22"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]
nox-poetry = "^0.8.6"
pytest = "^6.2.5"
wemake-python-styleguide = "^0.15.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
