[tool.poetry]
name = "pysemver"
version = "0.3.0"
description = ""
authors = ["Mauko Quiroga <mauko@pm.me>"]
packages = [{include = "pysemver", from = "src"}]

[tool.poetry.dependencies]
python = "~3.7 || ~3.8 || ~3.9"
numpy = ">=1.7, <1.22"
termcolor = "<2"
typing_extensions = { version = "<4", python = "~3.7" }

[tool.poetry.dev-dependencies]
nox-poetry = "<1"
pytest = "<7"
wemake-python-styleguide = "<1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
