[tool.poetry]
name = "pysemver"
version = "0.1.0"
description = ""
authors = ["Mauko Quiroga <mauko@pm.me>"]
packages = [{include = "pysemver", from = "src"}]

[tool.poetry.dependencies]
python = "~3.7 || ~3.8 || ~3.9 || ~3.10"
numpy = "~1.18 || ~1.19 || ~1.20 || ~1.21"
termcolor = "<2"
typing_extensions = { version = "<4", python = "~3.7" }

[tool.poetry.dev-dependencies]
nox = "2021.10.1"
pytest = "<7"
wemake-python-styleguide = "<1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
