[tool.poetry]
name = "pysemver"
version = "0.3.0"
description = ""
authors = ["Mauko Quiroga <mauko@pm.me>"]
packages = [{include = "pysemver", from = "src"}]

[tool.poetry.dependencies]
python = "~3.7 || ~3.8 || ~3.9"
funcy = "<2"
invoke = "<2"
numpy = ">=1.7, <1.22"
pipeop = "<1"
rich = "<11"
termcolor = "<2"
typing_extensions = { version = "<4", python = "~3.7" }

[tool.poetry.dev-dependencies]
coverage = { extras = ["toml"], version = "<7" }
nox-poetry = "<1"
pytest = "<7"
pytest-cov = "<4"
wemake-python-styleguide = "<1"

[tool.poetry.scripts]
pysemver = 'pysemver:main.run'

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["pysemver"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.pytest.ini_options]
addopts = "-qx --disable-pytest-warnings --doctest-modules"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
