name: Check Version

on: [ push ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    name: check-version

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout fixtures
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: maukoquiroga/mantic-fixtures
          path: tests/fixtures

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
          architecture: x64

      - name: Install dependencies
        run: make install

      - name: Check version
        run: nox -s check_version
