name: docs

on: [ push ]

jobs:
  docs:
    runs-on: ubuntu-latest

    name: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
          architecture: x64

      - name: Install dependencies
        run: make install

      - name: Run doc tasks
        run: nox -s "docs-3.9.7"
