name: Python Semantic Versioning

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        python: [3.7.12, 3.8.12, 3.9.7]
        numpy: [1.17.5, 1.18.5, 1.19.5, 1.20.3, 1.21.2]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: poetry run nox -s "test(${{ matrix.python }}/${{ matrix.numpy }})"
